# Generated by Django 4.2 on 2025-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0003_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'borrador'), ('publicado', 'publicado'), ('retirado', 'retirado')], default='borrador', max_length=10),
        ),
    ]
