# Generated by Django 5.2.7 on 2026-02-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0006_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link_mercadolibre',
            field=models.URLField(default=0, help_text='URL del producto en Mercado Libre', max_length=500),
        ),
    ]
