# Generated by Django 5.2.7 on 2026-02-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0007_producto_link_mercadolibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
