# Generated by Django 5.2.7 on 2026-02-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0008_producto_descripcion_alter_producto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_productos',
            field=models.IntegerField(default=0),
        ),
    ]
