# Generated by Django 5.2.7 on 2026-02-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0010_productoimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoimagen',
            old_name='imagen',
            new_name='imagen_secundaria',
        ),
    ]
